baseurl: "https://msg2020.pzhao.org/"
# languageCode: "en-us"
languageCode: "zh-cn"
# defaultContentLanguage: "en"
defaultContentLanguage: "zh"
title: "现代统计图形"
theme: "hugo-prose"
publishdir: "docs"
googleAnalytics: "UA-192936648-1"
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
paginate: 10

permalinks:
  post: "/:slug/"

outputs:
  home: [html, rss, json]

# some menu items were added via the `menu` option in YAML in posts
menu:
  header:
    - name: 搜索
      url: "#"
      identifier: menu-search
    - name: 订阅
      url: "index.xml"
  footer:
#    - name: 联系
#      url: "/404.html"
#      weight: 1
#    - name: 类别
#      url: "/categories/"
#      weight: 2
#      pre: "optional"
#    - name: 标签
#      url: "/tags/"
#      weight: 3
#      pre: "optional"
    - name: 回到顶部
      url: "#"

params:
  homePosts: 10
  mainSections: ["post", "work"]
  editLink: "https://github.com/pzhaonet/msg2020/edit/master/content/"
#  editLink: "https://github.com/yihui/hugo-prose/edit/master/exampleSite/content/"
  authorDelimiter: " / "
  pageFeatures: [+sidenotes]
  description: >
    《现代统计图形》主页。
  footer: >
    &copy; 版权所有，转载请注明出处和作者。<br>
    致谢：本站采用 [Hugo](https://gohugo.io/) 框架、[Prose](https://prose.yihui.org/about/) 主题、[R blogdown](https://bookdown.org/yihui/blogdown/) 包搭建，[GitHub](https://bookdown.org/yihui/blogdown/) 和 [Vercel](https://vercel.com/) 托管。

  license: >
    本文文字和图表使用知识共享许可协议 [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)，[源文件](https://github.com/pzhaonet/msg2020)采用 MIT 协议。
#    Text and figures are licensed under [Creative Commons Attribution CC BY
#    4.0](https://creativecommons.org/licenses/by/4.0/). The source code is
#    licensed under MIT. The full source is available at
#    https://github.com/yihui/hugo-prose.

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
